Repository SethMMorton/natsort, pull requests merged in 2018-11, with the labels that each got.

#83 Formal deprecation notices
  README.rst
  docs/changelog.rst
  docs/intro.rst
  natsort/__init__.py
  natsort/natsort.py
  natsort/ns_enum.py
  natsort/utils.py
  test_natsort/test_natsorted.py
  test_natsort/test_natsorted_convenience.py
  test_natsort/test_utils.py
Labels: documentation, maintainability

#84 Add support for very old versions of setuptools
  setup.py
Labels: bug, usability

#85 Make a better changelog
  CHANGELOG.rst
  README.rst
  docs/changelog.rst
Labels: documentation

#86 Remove pipenv dependency
  MANIFEST.in
  Pipfile
  README.rst
  dev-requirements.txt
  docs/intro.rst
  tox.ini
Labels: documentation, maintainability, usability

#88 Use `dist: xenial` in Travis to simplify configuration
  .travis.yml
Labels: maintainability
