Repository SethMMorton/natsort, pull requests merged in 2019-02, with the labels that each got.

#89 Specify long_description_content_type = text/x-rst
  setup.cfg
Labels: documentation

#81 Remove Deprecated APIs
  natsort/__init__.py
  natsort/__main__.py
  natsort/natsort.py
  natsort/ns_enum.py
  natsort/utils.py
  tests/test_natsorted_convenience.py
  tests/test_utils.py
Labels: maintainability, usability

#91 Update Travis-CI to support MacOS and Windows
  .travis.yml
  natsort/utils.py
  tests/test_natsort_keygen.py
Labels: maintainability
